{% set python_min = "3.10" %}
{% set name = "hdfmap" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hdfmap-{{ version }}.tar.gz
  sha256: 11d7b007e7f01f1c4aa4ec11ddff926f6d7f68e73b44b66d82877f4d3f54b5bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pytest
    - numpy
    - h5py
    - hdf5plugin
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - h5py
    - hdf5plugin
    - asteval

test:
  imports:
    - hdfmap
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Map objects within a HDF5 file and create a dataset namespace
  home: https://github.com/DiamondLightSource/hdfmap
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DanPorter
    - PeterC-DLS
