{% set python_min = "3.10" %}
{% set name = "hdfmap" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hdfmap-{{ version }}.tar.gz
  sha256: a9a1aa483cf09f6d5f0a5e111a9466a1a53bbf98353d0fbaa176f44dd4e0c99a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pytest
    - numpy >=1.19.3
    - h5py >=3.11.0
    - hdf5plugin
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - h5py
    - hdf5plugin

test:
  imports:
    - hdfmap
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Map objects within a HDF5 file and create a dataset namespace
  home: https://github.com/DiamondLightSource/hdfmap
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DanPorter
    - PeterC-DLS
