{% set python_min = "3.10" %}
{% set name = "hdfmap" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hdfmap-{{ version }}.tar.gz
  sha256: 0c96c619d4e152c1a1cdfd678a7373030d93c375323453338c4e3cd6769217d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pytest
    - numpy
    - h5py
    - hdf5plugin
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - h5py
    - hdf5plugin

test:
  imports:
    - hdfmap
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Map objects within a HDF5 file and create a dataset namespace
  home: https://github.com/DiamondLightSource/hdfmap
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DanPorter
    - PeterC-DLS
